# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.1'

gem 'rails', '~> 7.0.4', '>= 7.0.4.3'

# Solargraph
gem 'solargraph', require: false

# Basic
gem 'bootsnap', require: false
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Auth
gem 'devise_token_auth', '~> 1.2'

# Cors
gem 'rack-cors', '~> 2.0'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'faker'
  gem 'rspec-rails', '~> 6.0.1'
  gem 'shoulda-matchers', '~> 5.3.0'
end

group :development do
end
